spring:
  main:
    banner-mode: console
    log-startup-info: on

clojure-component:
  nrepl-port: 8190
  nrepl-start: true
  root-path: /clojure
  ws-path: /web-socket
  init-symbol: org.msync.spring-clj.core/main
